spring.application.name=ApiOmdb
omdb.api-key=e721ced8
omdb.base-url=http://www.omdbapi.com/
spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb
spring.jpa.hibernate.ddl-auto=update

